name: Relase
permissions:
  contents: write
on:
  push:
    branches:
      - master
jobs:
  Build-for-Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install more dependencies
      run: |
        sudo apt-get install -y \
          make \
          build-essential
    - name: Build
      run: |
          ./bootstrap.sh
          ./configure
          make
          make deb
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/minimdnsd_*.deb
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
